let map;
let infoWindow;
let infoSticky = false;

function initMap() {
    infoWindow = new google.maps.InfoWindow();

    map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: 39.8097343, lng: -98.5556199 },
        zoom: 4,
        styles: mapStyle,
    });
    map.data.setStyle(styleFeature);

//    loadData('https://docs.google.com/spreadsheets/d/e/2PACX-1vQQxOsSHBMWvepcnHSn2Sa1sIryADvJGg1DeduGNhVXp-0UD21ZGRAPZJOicIIjE0paZafFj0x6hH3t/pub?gid=1152466135&single=true&output=csv')

    eqfeed_callback(
        JSON.parse(`{"type":"FeatureCollection",
 "metadata":{"count":183},
 "features":
  [{"type":"Feature",
    "properties":
     {"District":"CROCKETT CO SCHOOL DISTRICT",
      "Location":"ALAMO, TN",
      "Total Classes":55,
      "Total Teachers":7,
      "Total Students":802,
      "Classes Per Teacher":7.86,
      "Students Per Class":14.58,
      "Algebra Classes":28,
      "Algebra Teachers":31,
      "Algebra Students":594},
    "geometry":{"type":"Point", "coordinates":[-89.1167, 35.7831]},
    "id":1},
   {"type":"Feature",
    "properties":
     {"District":"ANN ARBOR PUB SCHOOL DISTRICT",
      "Location":"ANN ARBOR, MI",
      "Total Classes":12,
      "Total Teachers":12,
      "Total Students":258,
      "Classes Per Teacher":1.0,
      "Students Per Class":21.5,
      "Algebra Classes":11,
      "Algebra Teachers":22,
      "Algebra Students":217},
    "geometry":{"type":"Point", "coordinates":[-83.7312, 42.2755]},
    "id":2},
   {"type":"Feature",
    "properties":
     {"District":"GLOBAL EDUCATIONAL EXCELLENCE",
      "Location":"ANN ARBOR, MI",
      "Total Classes":177,
      "Total Teachers":33,
      "Total Students":2285,
      "Classes Per Teacher":5.36,
      "Students Per Class":12.91,
      "Algebra Classes":37,
      "Algebra Teachers":54,
      "Algebra Students":1308},
    "geometry":{"type":"Point", "coordinates":[-83.7312, 42.2755]},
    "id":3},
   {"type":"Feature",
    "properties":
     {"District":"DESOTO CO SCHOOL DISTRICT",
      "Location":"ARCADIA, FL",
      "Total Classes":6,
      "Total Teachers":2,
      "Total Students":137,
      "Classes Per Teacher":3.0,
      "Students Per Class":22.83,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":139},
    "geometry":{"type":"Point", "coordinates":[-81.8587, 27.2214]},
    "id":4},
   {"type":"Feature",
    "properties":
     {"District":"ARLINGTON SCHOOL DISTRICT 16",
      "Location":"ARLINGTON, WA",
      "Total Classes":32,
      "Total Teachers":11,
      "Total Students":393,
      "Classes Per Teacher":2.91,
      "Students Per Class":12.28,
      "Algebra Classes":17,
      "Algebra Teachers":31,
      "Algebra Students":365},
    "geometry":{"type":"Point", "coordinates":[-122.1446, 48.1697]},
    "id":5},
   {"type":"Feature",
    "properties":
     {"District":"ATHENS AREA SCHOOL DISTRICT",
      "Location":"ATHENS, PA",
      "Total Classes":27,
      "Total Teachers":5,
      "Total Students":353,
      "Classes Per Teacher":5.4,
      "Students Per Class":13.07,
      "Algebra Classes":21,
      "Algebra Teachers":30,
      "Algebra Students":422},
    "geometry":{"type":"Point", "coordinates":[-76.5186, 41.9515]},
    "id":6},
   {"type":"Feature",
    "properties":
     {"District":"EANES IND SCHOOL DISTRICT",
      "Location":"AUSTIN, TX",
      "Total Classes":4,
      "Total Teachers":3,
      "Total Students":30,
      "Classes Per Teacher":1.33,
      "Students Per Class":7.5,
      "Algebra Classes":4,
      "Algebra Teachers":8,
      "Algebra Students":45},
    "geometry":{"type":"Point", "coordinates":[-97.7517, 30.3006]},
    "id":7},
   {"type":"Feature",
    "properties":
     {"District":"KENILWORTH SCIENCE AND TECHNOLOGY SCHOOL",
      "Location":"BATON ROUGE, LA",
      "Total Classes":2,
      "Total Teachers":2,
      "Total Students":27,
      "Classes Per Teacher":1.0,
      "Students Per Class":13.5,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":27},
    "geometry":{"type":"Point", "coordinates":[-91.131, 30.4419]},
    "id":8},
   {"type":"Feature",
    "properties":
     {"District":"NORTH MASON SCHOOL DIST 403",
      "Location":"BELFAIR, WA",
      "Total Classes":2,
      "Total Teachers":1,
      "Total Students":52,
      "Classes Per Teacher":2.0,
      "Students Per Class":26.0,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":52},
    "geometry":{"type":"Point", "coordinates":[-122.8487, 47.4495]},
    "id":9},
   {"type":"Feature",
    "properties":
     {"District":"BELLINGHAM SCHOOL DISTRICT 501",
      "Location":"BELLINGHAM, WA",
      "Total Classes":508,
      "Total Teachers":49,
      "Total Students":3743,
      "Classes Per Teacher":10.37,
      "Students Per Class":7.37,
      "Algebra Classes":165,
      "Algebra Teachers":193,
      "Algebra Students":4859},
    "geometry":{"type":"Point", "coordinates":[-122.4687, 48.7543]},
    "id":10},
   {"type":"Feature",
    "properties":
     {"District":"DESERT CHRISTIAN ACADEMY",
      "Location":"BERMUDA DUNES, CA",
      "Total Classes":41,
      "Total Teachers":5,
      "Total Students":325,
      "Classes Per Teacher":8.2,
      "Students Per Class":7.93,
      "Algebra Classes":8,
      "Algebra Teachers":8,
      "Algebra Students":124},
    "geometry":{"type":"Point", "coordinates":[-116.2874, 33.7435]},
    "id":11},
   {"type":"Feature",
    "properties":
     {"District":"BLAINE SCHOOL DISTRICT 503",
      "Location":"BLAINE, WA",
      "Total Classes":107,
      "Total Teachers":21,
      "Total Students":1180,
      "Classes Per Teacher":5.1,
      "Students Per Class":11.03,
      "Algebra Classes":22,
      "Algebra Teachers":30,
      "Algebra Students":584},
    "geometry":{"type":"Point", "coordinates":[-122.7414, 48.9839]},
    "id":12},
   {"type":"Feature",
    "properties":
     {"District":"BLOOMFIELD SCHOOL DISTRICT",
      "Location":"BLOOMFIELD, NJ",
      "Total Classes":99,
      "Total Teachers":16,
      "Total Students":583,
      "Classes Per Teacher":6.19,
      "Students Per Class":5.89,
      "Algebra Classes":35,
      "Algebra Teachers":43,
      "Algebra Students":826},
    "geometry":{"type":"Point", "coordinates":[-74.1854, 40.8068]},
    "id":13},
   {"type":"Feature",
    "properties":
     {"District":"NASHOBA REGIONAL SCH DISTRICT",
      "Location":"BOLTON, MA",
      "Total Classes":6,
      "Total Teachers":4,
      "Total Students":139,
      "Classes Per Teacher":1.5,
      "Students Per Class":23.17,
      "Algebra Classes":6,
      "Algebra Teachers":8,
      "Algebra Students":140},
    "geometry":{"type":"Point", "coordinates":[-71.6078, 42.4334]},
    "id":14},
   {"type":"Feature",
    "properties":
     {"District":"BRONX STUDIO SCHOOL FOR WRITERS AND ARTISTS - 08X269",
      "Location":"BRONX, NY",
      "Total Classes":13,
      "Total Teachers":3,
      "Total Students":328,
      "Classes Per Teacher":4.33,
      "Students Per Class":25.23,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":124},
    "geometry":{"type":"Point", "coordinates":[-73.8662, 40.8501]},
    "id":15},
   {"type":"Feature",
    "properties":
     {"District":
       "NYCDOE - 08X293 - RENAISSANCE HIGH SCHOOL FOR MUSICAL THEATER AND THE ARTS",
      "Location":"BRONX, NY",
      "Total Classes":2,
      "Total Teachers":2,
      "Total Students":32,
      "Classes Per Teacher":1.0,
      "Students Per Class":16.0,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":2},
    "geometry":{"type":"Point", "coordinates":[-73.8662, 40.8501]},
    "id":16},
   {"type":"Feature",
    "properties":
     {"District":"CONEY ISLAND PREP PUBLIC CS",
      "Location":"BROOKLYN, NY",
      "Total Classes":56,
      "Total Teachers":12,
      "Total Students":386,
      "Classes Per Teacher":4.67,
      "Students Per Class":6.89,
      "Algebra Classes":22,
      "Algebra Teachers":68,
      "Algebra Students":459},
    "geometry":{"type":"Point", "coordinates":[-73.9496, 40.6501]},
    "id":17},
   {"type":"Feature",
    "properties":
     {"District":"BROOKLYN CITY SCHOOL DISTRICT",
      "Location":"BROOKLYN, OH",
      "Total Classes":129,
      "Total Teachers":16,
      "Total Students":665,
      "Classes Per Teacher":8.06,
      "Students Per Class":5.16,
      "Algebra Classes":32,
      "Algebra Teachers":41,
      "Algebra Students":613},
    "geometry":{"type":"Point", "coordinates":[-81.7498, 41.4349]},
    "id":18},
   {"type":"Feature",
    "properties":
     {"District":"HAYWOOD CO SCHOOL DISTRICT",
      "Location":"BROWNSVILLE, TN",
      "Total Classes":101,
      "Total Teachers":11,
      "Total Students":1020,
      "Classes Per Teacher":9.18,
      "Students Per Class":10.1,
      "Algebra Classes":42,
      "Algebra Teachers":42,
      "Algebra Students":606},
    "geometry":{"type":"Point", "coordinates":[-89.2578, 35.589]},
    "id":19},
   {"type":"Feature",
    "properties":
     {"District":"BURNET CONS IND SCH DIST",
      "Location":"BURNET, TX",
      "Total Classes":9,
      "Total Teachers":3,
      "Total Students":183,
      "Classes Per Teacher":3.0,
      "Students Per Class":20.33,
      "Algebra Classes":9,
      "Algebra Teachers":9,
      "Algebra Students":186},
    "geometry":{"type":"Point", "coordinates":[-98.2382, 30.7496]},
    "id":20},
   {"type":"Feature",
    "properties":
     {"District":"CASHMERE SCHOOL DIST 222",
      "Location":"CASHMERE, WA",
      "Total Classes":4,
      "Total Teachers":2,
      "Total Students":84,
      "Classes Per Teacher":2.0,
      "Students Per Class":21.0,
      "Algebra Classes":4,
      "Algebra Teachers":6,
      "Algebra Students":89},
    "geometry":{"type":"Point", "coordinates":[-120.4671, 47.5175]},
    "id":21},
   {"type":"Feature",
    "properties":
     {"District":"QUEEN ANNES CO PUBLIC SD",
      "Location":"CENTREVILLE, MD",
      "Total Classes":524,
      "Total Teachers":85,
      "Total Students":4200,
      "Classes Per Teacher":6.16,
      "Students Per Class":8.02,
      "Algebra Classes":117,
      "Algebra Teachers":164,
      "Algebra Students":2606},
    "geometry":{"type":"Point", "coordinates":[-76.0631, 39.042]},
    "id":22},
   {"type":"Feature",
    "properties":
     {"District":"CHERRY HILL PUBLIC SCHOOL DIST",
      "Location":"CHERRY HILL, NJ",
      "Total Classes":32,
      "Total Teachers":12,
      "Total Students":369,
      "Classes Per Teacher":2.67,
      "Students Per Class":11.53,
      "Algebra Classes":23,
      "Algebra Teachers":47,
      "Algebra Students":494},
    "geometry":{"type":"Point", "coordinates":[-75.0117, 39.9384]},
    "id":23},
   {"type":"Feature",
    "properties":
     {"District":"CITY OF CHICAGO SD 299 - PULASKI ES",
      "Location":"CHICAGO, IL",
      "Total Classes":9,
      "Total Teachers":1,
      "Total Students":189,
      "Classes Per Teacher":9.0,
      "Students Per Class":21.0,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":194},
    "geometry":{"type":"Point", "coordinates":[-87.6862, 41.8373]},
    "id":24},
   {"type":"Feature",
    "properties":
     {"District":"CLEVELAND METRO SCHOOL DIST",
      "Location":"CLEVELAND, OH",
      "Total Classes":17,
      "Total Teachers":4,
      "Total Students":297,
      "Classes Per Teacher":4.25,
      "Students Per Class":17.47,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":17},
    "geometry":{"type":"Point", "coordinates":[-81.6805, 41.4767]},
    "id":25},
   {"type":"Feature",
    "properties":
     {"District":"COLUMBIA SCHOOL DISTRICT 93",
      "Location":"COLUMBIA, MO",
      "Total Classes":2,
      "Total Teachers":4,
      "Total Students":50,
      "Classes Per Teacher":0.5,
      "Students Per Class":25.0,
      "Algebra Classes":2,
      "Algebra Teachers":4,
      "Algebra Students":51},
    "geometry":{"type":"Point", "coordinates":[-92.3255, 38.9477]},
    "id":26},
   {"type":"Feature",
    "properties":
     {"District":"COMFORT IND SCHOOL DISTRICT",
      "Location":"COMFORT, TX",
      "Total Classes":9,
      "Total Teachers":5,
      "Total Students":99,
      "Classes Per Teacher":1.8,
      "Students Per Class":11.0,
      "Algebra Classes":1,
      "Algebra Teachers":2,
      "Algebra Students":22},
    "geometry":{"type":"Point", "coordinates":[-98.904, 29.9714]},
    "id":27},
   {"type":"Feature",
    "properties":
     {"District":"ORANGE COUNTY DEPT OF EDUCATION",
      "Location":"COSTA MESA, CA",
      "Total Classes":557,
      "Total Teachers":83,
      "Total Students":2766,
      "Classes Per Teacher":6.71,
      "Students Per Class":4.97,
      "Algebra Classes":278,
      "Algebra Teachers":278,
      "Algebra Students":7546},
    "geometry":{"type":"Point", "coordinates":[-117.9135, 33.6667]},
    "id":28},
   {"type":"Feature",
    "properties":
     {"District":"DIXIE CO SCHOOL DISTRICT",
      "Location":"CROSS CITY, FL",
      "Total Classes":7,
      "Total Teachers":1,
      "Total Students":113,
      "Classes Per Teacher":7.0,
      "Students Per Class":16.14,
      "Algebra Classes":7,
      "Algebra Teachers":7,
      "Algebra Students":127},
    "geometry":{"type":"Point", "coordinates":[-83.1248, 29.6386]},
    "id":29},
   {"type":"Feature",
    "properties":
     {"District":"BRIGHT STAR SCHOOLS",
      "Location":"CULVER CITY, CA",
      "Total Classes":160,
      "Total Teachers":25,
      "Total Students":1993,
      "Classes Per Teacher":6.4,
      "Students Per Class":12.46,
      "Algebra Classes":63,
      "Algebra Teachers":129,
      "Algebra Students":2145},
    "geometry":{"type":"Point", "coordinates":[-118.3968, 34.0058]},
    "id":30},
   {"type":"Feature",
    "properties":
     {"District":"DANVILLE PUBLIC SCHOOL DIST",
      "Location":"DANVILLE, VA",
      "Total Classes":2,
      "Total Teachers":1,
      "Total Students":48,
      "Classes Per Teacher":2.0,
      "Students Per Class":24.0,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":48},
    "geometry":{"type":"Point", "coordinates":[-79.4088, 36.5831]},
    "id":31},
   {"type":"Feature",
    "properties":
     {"District":"K12 LIFT",
      "Location":"DELAND, FL",
      "Total Classes":1,
      "Total Teachers":1,
      "Total Students":1,
      "Classes Per Teacher":1.0,
      "Students Per Class":1.0,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":1},
    "geometry":{"type":"Point", "coordinates":[-81.2873, 29.0224]},
    "id":32},
   {"type":"Feature",
    "properties":
     {"District":"DELHI CHARTER SCHOOL",
      "Location":"DELHI, LA",
      "Total Classes":49,
      "Total Teachers":10,
      "Total Students":448,
      "Classes Per Teacher":4.9,
      "Students Per Class":9.14,
      "Algebra Classes":8,
      "Algebra Teachers":14,
      "Algebra Students":185},
    "geometry":{"type":"Point", "coordinates":[-91.49, 32.4529]},
    "id":33},
   {"type":"Feature",
    "properties":
     {"District":"MT BAKER SCHOOL DISTRICT 507",
      "Location":"DEMING, WA",
      "Total Classes":2,
      "Total Teachers":2,
      "Total Students":38,
      "Classes Per Teacher":1.0,
      "Students Per Class":19.0,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":38},
    "geometry":{"type":"Point", "coordinates":[-122.2313, 48.8381]},
    "id":34},
   {"type":"Feature",
    "properties":
     {"District":"CAROLINE CO SCHOOL DISTRICT",
      "Location":"DENTON, MD",
      "Total Classes":141,
      "Total Teachers":22,
      "Total Students":1846,
      "Classes Per Teacher":6.41,
      "Students Per Class":13.09,
      "Algebra Classes":58,
      "Algebra Teachers":58,
      "Algebra Students":1421},
    "geometry":{"type":"Point", "coordinates":[-75.8264, 38.877]},
    "id":35},
   {"type":"Feature",
    "properties":
     {"District":"DOVER PUBLIC SCHOOL DISTRICT",
      "Location":"DOVER, NJ",
      "Total Classes":87,
      "Total Teachers":13,
      "Total Students":934,
      "Classes Per Teacher":6.69,
      "Students Per Class":10.74,
      "Algebra Classes":47,
      "Algebra Teachers":49,
      "Algebra Students":1040},
    "geometry":{"type":"Point", "coordinates":[-74.5597, 40.8859]},
    "id":36},
   {"type":"Feature",
    "properties":
     {"District":"CENTRAL UNION HIGH SCH DIST",
      "Location":"EL CENTRO, CA",
      "Total Classes":12,
      "Total Teachers":6,
      "Total Students":343,
      "Classes Per Teacher":2.0,
      "Students Per Class":28.58,
      "Algebra Classes":12,
      "Algebra Teachers":12,
      "Algebra Students":353},
    "geometry":{"type":"Point", "coordinates":[-115.5586, 32.7867]},
    "id":37},
   {"type":"Feature",
    "properties":
     {"District":"ELIZABETH SCHOOL DISTRICT",
      "Location":"ELIZABETH, NJ",
      "Total Classes":1383,
      "Total Teachers":237,
      "Total Students":10622,
      "Classes Per Teacher":5.84,
      "Students Per Class":7.68,
      "Algebra Classes":249,
      "Algebra Teachers":286,
      "Algebra Students":5495},
    "geometry":{"type":"Point", "coordinates":[-74.1912, 40.6657]},
    "id":38},
   {"type":"Feature",
    "properties":
     {"District":"ELMA SCHOOL DISTRICT 68",
      "Location":"ELMA, WA",
      "Total Classes":8,
      "Total Teachers":2,
      "Total Students":178,
      "Classes Per Teacher":4.0,
      "Students Per Class":22.25,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":72},
    "geometry":{"type":"Point", "coordinates":[-123.4112, 47.0055]},
    "id":39},
   {"type":"Feature",
    "properties":
     {"District":"ENTIAT SCHOOL DISTRICT 127",
      "Location":"ENTIAT, WA",
      "Total Classes":12,
      "Total Teachers":3,
      "Total Students":75,
      "Classes Per Teacher":4.0,
      "Students Per Class":6.25,
      "Algebra Classes":4,
      "Algebra Teachers":6,
      "Algebra Students":76},
    "geometry":{"type":"Point", "coordinates":[-120.2175, 47.678]},
    "id":40},
   {"type":"Feature",
    "properties":
     {"District":"FAIRVIEW AREA SCHOOL DISTRICT",
      "Location":"FAIRVIEW, MI",
      "Total Classes":22,
      "Total Teachers":4,
      "Total Students":303,
      "Classes Per Teacher":5.5,
      "Students Per Class":13.77,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":88},
    "geometry":{"type":"Point", "coordinates":[-84.0507, 44.7251]},
    "id":41},
   {"type":"Feature",
    "properties":
     {"District":"FARMINGTON MUN SCHOOL DIST 5",
      "Location":"FARMINGTON, NM",
      "Total Classes":297,
      "Total Teachers":75,
      "Total Students":5480,
      "Classes Per Teacher":3.96,
      "Students Per Class":18.45,
      "Algebra Classes":64,
      "Algebra Teachers":66,
      "Algebra Students":1555},
    "geometry":{"type":"Point", "coordinates":[-108.1823, 36.7555]},
    "id":42},
   {"type":"Feature",
    "properties":
     {"District":"FERGUSON-FLORISSANT SD R2",
      "Location":"FLORISSANT, MO",
      "Total Classes":15,
      "Total Teachers":4,
      "Total Students":144,
      "Classes Per Teacher":3.75,
      "Students Per Class":9.6,
      "Algebra Classes":15,
      "Algebra Teachers":18,
      "Algebra Students":270},
    "geometry":{"type":"Point", "coordinates":[-90.3269, 38.7996]},
    "id":43},
   {"type":"Feature",
    "properties":
     {"District":"FT WAYNE CMTY SCHOOL DIST",
      "Location":"FORT WAYNE, IN",
      "Total Classes":4277,
      "Total Teachers":235,
      "Total Students":18367,
      "Classes Per Teacher":18.2,
      "Students Per Class":4.29,
      "Algebra Classes":960,
      "Algebra Teachers":1227,
      "Algebra Students":23909},
    "geometry":{"type":"Point", "coordinates":[-85.1436, 41.0885]},
    "id":44},
   {"type":"Feature",
    "properties":
     {"District":"LEYDEN CMTY HIGH SCH DIST 212",
      "Location":"FRANKLIN PARK, IL",
      "Total Classes":126,
      "Total Teachers":26,
      "Total Students":1456,
      "Classes Per Teacher":4.85,
      "Students Per Class":11.56,
      "Algebra Classes":43,
      "Algebra Teachers":45,
      "Algebra Students":940},
    "geometry":{"type":"Point", "coordinates":[-87.8794, 41.936]},
    "id":45},
   {"type":"Feature",
    "properties":
     {"District":"FREDERICK CO PUBLIC SCH DIST",
      "Location":"FREDERICK, MD",
      "Total Classes":15,
      "Total Teachers":28,
      "Total Students":246,
      "Classes Per Teacher":0.54,
      "Students Per Class":16.4,
      "Algebra Classes":15,
      "Algebra Teachers":34,
      "Algebra Students":269},
    "geometry":{"type":"Point", "coordinates":[-77.4157, 39.4336]},
    "id":46},
   {"type":"Feature",
    "properties":
     {"District":"BRAZOSPORT IND SCHOOL DIST",
      "Location":"FREEPORT, TX",
      "Total Classes":138,
      "Total Teachers":29,
      "Total Students":627,
      "Classes Per Teacher":4.76,
      "Students Per Class":4.54,
      "Algebra Classes":25,
      "Algebra Teachers":40,
      "Algebra Students":412},
    "geometry":{"type":"Point", "coordinates":[-95.3602, 28.9454]},
    "id":47},
   {"type":"Feature",
    "properties":
     {"District":"GALVESTON IND SCHOOL DISTRICT",
      "Location":"GALVESTON, TX",
      "Total Classes":1,
      "Total Teachers":2,
      "Total Students":13,
      "Classes Per Teacher":0.5,
      "Students Per Class":13.0,
      "Algebra Classes":1,
      "Algebra Teachers":2,
      "Algebra Students":13},
    "geometry":{"type":"Point", "coordinates":[-94.891, 29.2487]},
    "id":48},
   {"type":"Feature",
    "properties":
     {"District":"GARDEN CITY UNIF SCH DIST 457",
      "Location":"GARDEN CITY, KS",
      "Total Classes":92,
      "Total Teachers":22,
      "Total Students":1122,
      "Classes Per Teacher":4.18,
      "Students Per Class":12.2,
      "Algebra Classes":59,
      "Algebra Teachers":85,
      "Algebra Students":1646},
    "geometry":{"type":"Point", "coordinates":[-100.8528, 37.9754]},
    "id":49},
   {"type":"Feature",
    "properties":
     {"District":"GILBERT UNIFIED SCH DIST 41",
      "Location":"GILBERT, AZ",
      "Total Classes":8,
      "Total Teachers":4,
      "Total Students":145,
      "Classes Per Teacher":2.0,
      "Students Per Class":18.13,
      "Algebra Classes":8,
      "Algebra Teachers":8,
      "Algebra Students":177},
    "geometry":{"type":"Point", "coordinates":[-111.7463, 33.3103]},
    "id":50},
   {"type":"Feature",
    "properties":
     {"District":"MESA CO VALLEY SCHOOL DIST 51",
      "Location":"GRAND JCT, CO",
      "Total Classes":18,
      "Total Teachers":4,
      "Total Students":29,
      "Classes Per Teacher":4.5,
      "Students Per Class":1.61,
      "Algebra Classes":4,
      "Algebra Teachers":8,
      "Algebra Students":7},
    "geometry":{"type":"Point", "coordinates":[-108.5673, 39.0877]},
    "id":51},
   {"type":"Feature",
    "properties":
     {"District":"GRANITE FALLS SCHOOL DIST 332",
      "Location":"GRANITE FALLS, WA",
      "Total Classes":3,
      "Total Teachers":1,
      "Total Students":46,
      "Classes Per Teacher":3.0,
      "Students Per Class":15.33,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":54},
    "geometry":{"type":"Point", "coordinates":[-121.9704, 48.0874]},
    "id":52},
   {"type":"Feature",
    "properties":
     {"District":"HANOVER PUBLIC SCHOOL DISTRICT",
      "Location":"HANOVER, PA",
      "Total Classes":4,
      "Total Teachers":2,
      "Total Students":71,
      "Classes Per Teacher":2.0,
      "Students Per Class":17.75,
      "Algebra Classes":4,
      "Algebra Teachers":4,
      "Algebra Students":71},
    "geometry":{"type":"Point", "coordinates":[-76.9835, 39.8117]},
    "id":53},
   {"type":"Feature",
    "properties":
     {"District":"HAYSVILLE UNIF SCH DIST 261",
      "Location":"HAYSVILLE, KS",
      "Total Classes":239,
      "Total Teachers":23,
      "Total Students":2325,
      "Classes Per Teacher":10.39,
      "Students Per Class":9.73,
      "Algebra Classes":74,
      "Algebra Teachers":74,
      "Algebra Students":2040},
    "geometry":{"type":"Point", "coordinates":[-97.3527, 37.5649]},
    "id":54},
   {"type":"Feature",
    "properties":
     {"District":"MIDWAY IND SCHOOL DISTRICT",
      "Location":"HENRIETTA, TX",
      "Total Classes":57,
      "Total Teachers":10,
      "Total Students":601,
      "Classes Per Teacher":5.7,
      "Students Per Class":10.54,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":87},
    "geometry":{"type":"Point", "coordinates":[-98.1925, 33.8147]},
    "id":55},
   {"type":"Feature",
    "properties":
     {"District":"BETA ACADEMY",
      "Location":"HOUSTON, TX",
      "Total Classes":29,
      "Total Teachers":4,
      "Total Students":558,
      "Classes Per Teacher":7.25,
      "Students Per Class":19.24,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":96},
    "geometry":{"type":"Point", "coordinates":[-95.3905, 29.7869]},
    "id":56},
   {"type":"Feature",
    "properties":
     {"District":"ATASCOCITA HIGH SCHOOL",
      "Location":"HUMBLE, TX",
      "Total Classes":4,
      "Total Teachers":1,
      "Total Students":39,
      "Classes Per Teacher":4.0,
      "Students Per Class":9.75,
      "Algebra Classes":4,
      "Algebra Teachers":4,
      "Algebra Students":39},
    "geometry":{"type":"Point", "coordinates":[-95.2655, 29.9921]},
    "id":57},
   {"type":"Feature",
    "properties":
     {"District":"HUNTSVILLE IND SCHOOL DIST",
      "Location":"HUNTSVILLE, TX",
      "Total Classes":308,
      "Total Teachers":42,
      "Total Students":3081,
      "Classes Per Teacher":7.33,
      "Students Per Class":10.0,
      "Algebra Classes":64,
      "Algebra Teachers":64,
      "Algebra Students":1473},
    "geometry":{"type":"Point", "coordinates":[-95.5545, 30.705]},
    "id":58},
   {"type":"Feature",
    "properties":
     {"District":"CHRISTEL HOUSE SCHOOLS",
      "Location":"INDANAPOLIS, IN",
      "Total Classes":6,
      "Total Teachers":5,
      "Total Students":189,
      "Classes Per Teacher":1.2,
      "Students Per Class":31.5,
      "Algebra Classes":3,
      "Algebra Teachers":7,
      "Algebra Students":137},
    "geometry":{"type":"Point", "coordinates":[-86.1458, 39.7771]},
    "id":59},
   {"type":"Feature",
    "properties":
     {"District":"MSD OF PIKE TWP",
      "Location":"INDIANAPOLIS, IN",
      "Total Classes":389,
      "Total Teachers":33,
      "Total Students":3246,
      "Classes Per Teacher":11.79,
      "Students Per Class":8.34,
      "Algebra Classes":176,
      "Algebra Teachers":176,
      "Algebra Students":4054},
    "geometry":{"type":"Point", "coordinates":[-86.1458, 39.7771]},
    "id":60},
   {"type":"Feature",
    "properties":
     {"District":"VICTORY COLLEGE PREP",
      "Location":"INDIANAPOLIS, IN",
      "Total Classes":116,
      "Total Teachers":9,
      "Total Students":599,
      "Classes Per Teacher":12.89,
      "Students Per Class":5.16,
      "Algebra Classes":29,
      "Algebra Teachers":29,
      "Algebra Students":931},
    "geometry":{"type":"Point", "coordinates":[-86.1458, 39.7771]},
    "id":61},
   {"type":"Feature",
    "properties":
     {"District":"INGLEWOOD UNIFIED SCHOOL DIST",
      "Location":"INGLEWOOD, CA",
      "Total Classes":25,
      "Total Teachers":8,
      "Total Students":657,
      "Classes Per Teacher":3.13,
      "Students Per Class":26.28,
      "Algebra Classes":10,
      "Algebra Teachers":11,
      "Algebra Students":264},
    "geometry":{"type":"Point", "coordinates":[-118.3444, 33.9566]},
    "id":62},
   {"type":"Feature",
    "properties":
     {"District":"CALCASIEU PARISH PUBLIC SCHOOLS",
      "Location":"LAKE CHARLES, LA",
      "Total Classes":865,
      "Total Teachers":145,
      "Total Students":6879,
      "Classes Per Teacher":5.97,
      "Students Per Class":7.95,
      "Algebra Classes":136,
      "Algebra Teachers":171,
      "Algebra Students":2100},
    "geometry":{"type":"Point", "coordinates":[-93.2141, 30.2022]},
    "id":63},
   {"type":"Feature",
    "properties":
     {"District":"VERNON PARISH SCHOOL DISTRICT",
      "Location":"LEESVILLE, LA",
      "Total Classes":442,
      "Total Teachers":63,
      "Total Students":3982,
      "Classes Per Teacher":7.02,
      "Students Per Class":9.01,
      "Algebra Classes":122,
      "Algebra Teachers":126,
      "Algebra Students":2992},
    "geometry":{"type":"Point", "coordinates":[-93.2741, 31.1398]},
    "id":64},
   {"type":"Feature",
    "properties":
     {"District":"CAPE HENLOPEN SCHOOL DISTRICT",
      "Location":"LEWES, DE",
      "Total Classes":37,
      "Total Teachers":12,
      "Total Students":953,
      "Classes Per Teacher":3.08,
      "Students Per Class":25.76,
      "Algebra Classes":10,
      "Algebra Teachers":14,
      "Algebra Students":252},
    "geometry":{"type":"Point", "coordinates":[-75.1454, 38.7781]},
    "id":65},
   {"type":"Feature",
    "properties":
     {"District":"LITTLETON PUBLIC SCH DIST 6",
      "Location":"LITTLETON, CO",
      "Total Classes":72,
      "Total Teachers":12,
      "Total Students":515,
      "Classes Per Teacher":6.0,
      "Students Per Class":7.15,
      "Algebra Classes":45,
      "Algebra Teachers":45,
      "Algebra Students":1065},
    "geometry":{"type":"Point", "coordinates":[-105.0188, 39.5915]},
    "id":66},
   {"type":"Feature",
    "properties":
     {"District":"LIVINGSTON ISD",
      "Location":"LIVINGSTON, TX",
      "Total Classes":226,
      "Total Teachers":20,
      "Total Students":1282,
      "Classes Per Teacher":11.3,
      "Students Per Class":5.67,
      "Algebra Classes":20,
      "Algebra Teachers":20,
      "Algebra Students":270},
    "geometry":{"type":"Point", "coordinates":[-94.9381, 30.71]},
    "id":67},
   {"type":"Feature",
    "properties":
     {"District":"OCEAN BEACH SCH DIST 101",
      "Location":"LONG BEACH, WA",
      "Total Classes":10,
      "Total Teachers":4,
      "Total Students":202,
      "Classes Per Teacher":2.5,
      "Students Per Class":20.2,
      "Algebra Classes":4,
      "Algebra Teachers":6,
      "Algebra Students":156},
    "geometry":{"type":"Point", "coordinates":[-124.0556, 46.3559]},
    "id":68},
   {"type":"Feature",
    "properties":
     {"District":"LONGVIEW SCHOOL DIST 122",
      "Location":"LONGVIEW, WA",
      "Total Classes":12,
      "Total Teachers":2,
      "Total Students":91,
      "Classes Per Teacher":6.0,
      "Students Per Class":7.58,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":75},
    "geometry":{"type":"Point", "coordinates":[-122.963, 46.146]},
    "id":69},
   {"type":"Feature",
    "properties":
     {"District":"LUBBOCK IND SCHOOL DISTRICT",
      "Location":"LUBBOCK, TX",
      "Total Classes":7,
      "Total Teachers":4,
      "Total Students":142,
      "Classes Per Teacher":1.75,
      "Students Per Class":20.29,
      "Algebra Classes":7,
      "Algebra Teachers":7,
      "Algebra Students":151},
    "geometry":{"type":"Point", "coordinates":[-101.8871, 33.5642]},
    "id":70},
   {"type":"Feature",
    "properties":
     {"District":"EDMONDS SCHOOL DISTRICT 15",
      "Location":"LYNNWOOD, WA",
      "Total Classes":42,
      "Total Teachers":16,
      "Total Students":623,
      "Classes Per Teacher":2.63,
      "Students Per Class":14.83,
      "Algebra Classes":20,
      "Algebra Teachers":26,
      "Algebra Students":546},
    "geometry":{"type":"Point", "coordinates":[-122.3035, 47.8285]},
    "id":71},
   {"type":"Feature",
    "properties":
     {"District":"MANOR IND SCHOOL DISTRICT",
      "Location":"MANOR, TX",
      "Total Classes":17,
      "Total Teachers":7,
      "Total Students":317,
      "Classes Per Teacher":2.43,
      "Students Per Class":18.65,
      "Algebra Classes":11,
      "Algebra Teachers":11,
      "Algebra Students":294},
    "geometry":{"type":"Point", "coordinates":[-97.523, 30.3563]},
    "id":72},
   {"type":"Feature",
    "properties":
     {"District":"RED RIVER CHARTER ACADEMY",
      "Location":"MARKSVILLE, LA",
      "Total Classes":91,
      "Total Teachers":19,
      "Total Students":506,
      "Classes Per Teacher":4.79,
      "Students Per Class":5.56,
      "Algebra Classes":12,
      "Algebra Teachers":18,
      "Algebra Students":166},
    "geometry":{"type":"Point", "coordinates":[-92.0652, 31.1247]},
    "id":73},
   {"type":"Feature",
    "properties":
     {"District":"WAHLUKE SCHOOL DISTRICT 73",
      "Location":"MATTAWA, WA",
      "Total Classes":12,
      "Total Teachers":4,
      "Total Students":197,
      "Classes Per Teacher":3.0,
      "Students Per Class":16.42,
      "Algebra Classes":4,
      "Algebra Teachers":4,
      "Algebra Students":91},
    "geometry":{"type":"Point", "coordinates":[-119.9019, 46.7364]},
    "id":74},
   {"type":"Feature",
    "properties":
     {"District":"MAYWOOD SCHOOL DISTRICT 46",
      "Location":"MAYWOOD, NE",
      "Total Classes":20,
      "Total Teachers":4,
      "Total Students":78,
      "Classes Per Teacher":5.0,
      "Students Per Class":3.9,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":53},
    "geometry":{"type":"Point", "coordinates":[-100.6222, 40.6587]},
    "id":75},
   {"type":"Feature",
    "properties":
     {"District":"MEDICAL LAKE SCHOOL DIST 326",
      "Location":"MEDICAL LAKE, WA",
      "Total Classes":4,
      "Total Teachers":2,
      "Total Students":61,
      "Classes Per Teacher":2.0,
      "Students Per Class":15.25,
      "Algebra Classes":4,
      "Algebra Teachers":4,
      "Algebra Students":62},
    "geometry":{"type":"Point", "coordinates":[-117.6893, 47.5712]},
    "id":76},
   {"type":"Feature",
    "properties":
     {"District":"SIMPSON CO SCHOOL DISTRICT",
      "Location":"MENDENHALL, MS",
      "Total Classes":42,
      "Total Teachers":5,
      "Total Students":551,
      "Classes Per Teacher":8.4,
      "Students Per Class":13.12,
      "Algebra Classes":29,
      "Algebra Teachers":29,
      "Algebra Students":657},
    "geometry":{"type":"Point", "coordinates":[-89.8694, 31.9609]},
    "id":77},
   {"type":"Feature",
    "properties":
     {"District":"WEST ST. PAUL 197",
      "Location":"MENDOTA HEIGHTS, MN",
      "Total Classes":1,
      "Total Teachers":1,
      "Total Students":12,
      "Classes Per Teacher":1.0,
      "Students Per Class":12.0,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":12},
    "geometry":{"type":"Point", "coordinates":[-93.14, 44.8815]},
    "id":78},
   {"type":"Feature",
    "properties":
     {"District":"MICHIGAN CITY AREA SCHOOLS",
      "Location":"MICHIGAN CITY, IN",
      "Total Classes":10,
      "Total Teachers":2,
      "Total Students":131,
      "Classes Per Teacher":5.0,
      "Students Per Class":13.1,
      "Algebra Classes":10,
      "Algebra Teachers":10,
      "Algebra Students":202},
    "geometry":{"type":"Point", "coordinates":[-86.8705, 41.7098]},
    "id":79},
   {"type":"Feature",
    "properties":
     {"District":"MILTON FREEWATER USD 7",
      "Location":"MILTON FRWTR, OR",
      "Total Classes":68,
      "Total Teachers":7,
      "Total Students":561,
      "Classes Per Teacher":9.71,
      "Students Per Class":8.25,
      "Algebra Classes":30,
      "Algebra Teachers":30,
      "Algebra Students":773},
    "geometry":{"type":"Point", "coordinates":[-118.3913, 45.9348]},
    "id":80},
   {"type":"Feature",
    "properties":
     {"District":"WEBSTER PARISH SCHOOL DIST",
      "Location":"MINDEN, LA",
      "Total Classes":278,
      "Total Teachers":49,
      "Total Students":2868,
      "Classes Per Teacher":5.67,
      "Students Per Class":10.32,
      "Algebra Classes":103,
      "Algebra Teachers":124,
      "Algebra Students":2943},
    "geometry":{"type":"Point", "coordinates":[-93.2762, 32.6187]},
    "id":81},
   {"type":"Feature",
    "properties":
     {"District":"PENN HARRIS MADISON SCH CORP",
      "Location":"MISHAWAKA, IN",
      "Total Classes":327,
      "Total Teachers":30,
      "Total Students":4675,
      "Classes Per Teacher":10.9,
      "Students Per Class":14.3,
      "Algebra Classes":163,
      "Algebra Teachers":181,
      "Algebra Students":4758},
    "geometry":{"type":"Point", "coordinates":[-86.1669, 41.6736]},
    "id":82},
   {"type":"Feature",
    "properties":
     {"District":"FOSTER GLOCESTER REGIONAL SD",
      "Location":"N SCITUATE, RI",
      "Total Classes":56,
      "Total Teachers":16,
      "Total Students":868,
      "Classes Per Teacher":3.5,
      "Students Per Class":15.5,
      "Algebra Classes":11,
      "Algebra Teachers":12,
      "Algebra Students":223},
    "geometry":{"type":"Point", "coordinates":[-71.5871, 41.8327]},
    "id":83},
   {"type":"Feature",
    "properties":
     {"District":"SCITUATE SCHOOL DISTRICT",
      "Location":"N SCITUATE, RI",
      "Total Classes":46,
      "Total Teachers":14,
      "Total Students":510,
      "Classes Per Teacher":3.29,
      "Students Per Class":11.09,
      "Algebra Classes":24,
      "Algebra Teachers":33,
      "Algebra Students":439},
    "geometry":{"type":"Point", "coordinates":[-71.5871, 41.8327]},
    "id":84},
   {"type":"Feature",
    "properties":
     {"District":"KIPP NEW ORLEANS",
      "Location":"NEW ORLEANS, LA",
      "Total Classes":305,
      "Total Teachers":30,
      "Total Students":2415,
      "Classes Per Teacher":10.17,
      "Students Per Class":7.92,
      "Algebra Classes":132,
      "Algebra Teachers":138,
      "Algebra Students":3208},
    "geometry":{"type":"Point", "coordinates":[-89.9288, 30.0687]},
    "id":85},
   {"type":"Feature",
    "properties":
     {"District":"NEW ORLEANS COLLEGE PREP",
      "Location":"NEW ORLEANS, LA",
      "Total Classes":8,
      "Total Teachers":3,
      "Total Students":142,
      "Classes Per Teacher":2.67,
      "Students Per Class":17.75,
      "Algebra Classes":4,
      "Algebra Teachers":4,
      "Algebra Students":137},
    "geometry":{"type":"Point", "coordinates":[-89.9288, 30.0687]},
    "id":86},
   {"type":"Feature",
    "properties":
     {"District":"RENEW ACCELERATED HIGH SCHOOL",
      "Location":"NEW ORLEANS, LA",
      "Total Classes":25,
      "Total Teachers":3,
      "Total Students":205,
      "Classes Per Teacher":8.33,
      "Students Per Class":8.2,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":61},
    "geometry":{"type":"Point", "coordinates":[-89.9288, 30.0687]},
    "id":87},
   {"type":"Feature",
    "properties":
     {"District":"SOPHIE B. WRIGHT CHARTER SCHOOL",
      "Location":"NEW ORLEANS, LA",
      "Total Classes":52,
      "Total Teachers":6,
      "Total Students":602,
      "Classes Per Teacher":8.67,
      "Students Per Class":11.58,
      "Algebra Classes":24,
      "Algebra Teachers":39,
      "Algebra Students":536},
    "geometry":{"type":"Point", "coordinates":[-89.9288, 30.0687]},
    "id":88},
   {"type":"Feature",
    "properties":
     {"District":"WARREN EASTON CHARTER HS",
      "Location":"NEW ORLEANS, LA",
      "Total Classes":86,
      "Total Teachers":12,
      "Total Students":1451,
      "Classes Per Teacher":7.17,
      "Students Per Class":16.87,
      "Algebra Classes":39,
      "Algebra Teachers":39,
      "Algebra Students":948},
    "geometry":{"type":"Point", "coordinates":[-89.9288, 30.0687]},
    "id":89},
   {"type":"Feature",
    "properties":
     {"District":"NYC PROFESSIONAL LEARNING PARTNERSHIPS",
      "Location":"NEW YORK CITY, NY",
      "Total Classes":255,
      "Total Teachers":51,
      "Total Students":5740,
      "Classes Per Teacher":5.0,
      "Students Per Class":22.51,
      "Algebra Classes":168,
      "Algebra Teachers":195,
      "Algebra Students":4829},
    "geometry":{"type":"Point", "coordinates":[-73.9249, 40.6943]},
    "id":90},
   {"type":"Feature",
    "properties":
     {"District":"WORCESTER CO PUBLIC SCH DIST",
      "Location":"NEWARK, MD",
      "Total Classes":36,
      "Total Teachers":6,
      "Total Students":357,
      "Classes Per Teacher":6.0,
      "Students Per Class":9.92,
      "Algebra Classes":33,
      "Algebra Teachers":33,
      "Algebra Students":722},
    "geometry":{"type":"Point", "coordinates":[-75.2735, 38.2749]},
    "id":91},
   {"type":"Feature",
    "properties":
     {"District":"NEWTON UNIFIED SCH DIST 373",
      "Location":"NEWTON, KS",
      "Total Classes":5,
      "Total Teachers":2,
      "Total Students":97,
      "Classes Per Teacher":2.5,
      "Students Per Class":19.4,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":29},
    "geometry":{"type":"Point", "coordinates":[-97.3463, 38.0364]},
    "id":92},
   {"type":"Feature",
    "properties":
     {"District":"HAVERHILL COOPERATIVE SCHOOL DISTRICT",
      "Location":"NORTH HAVERHILL, NH",
      "Total Classes":4,
      "Total Teachers":1,
      "Total Students":51,
      "Classes Per Teacher":4.0,
      "Students Per Class":12.75,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":51},
    "geometry":{"type":"Point", "coordinates":[-72.0272, 44.0938]},
    "id":93},
   {"type":"Feature",
    "properties":
     {"District":"N ST PAUL MPLWD OAKDALE SD 622",
      "Location":"NORTH ST PAUL, MN",
      "Total Classes":6,
      "Total Teachers":8,
      "Total Students":105,
      "Classes Per Teacher":0.75,
      "Students Per Class":17.5,
      "Algebra Classes":6,
      "Algebra Teachers":11,
      "Algebra Students":111},
    "geometry":{"type":"Point", "coordinates":[-92.9995, 45.0137]},
    "id":94},
   {"type":"Feature",
    "properties":
     {"District":"ORANGE PUBLIC SCHOOL DISTRICT",
      "Location":"ORANGE, NJ",
      "Total Classes":48,
      "Total Teachers":11,
      "Total Students":555,
      "Classes Per Teacher":4.36,
      "Students Per Class":11.56,
      "Algebra Classes":21,
      "Algebra Teachers":21,
      "Algebra Students":368},
    "geometry":{"type":"Point", "coordinates":[-74.2326, 40.7706]},
    "id":95},
   {"type":"Feature",
    "properties":
     {"District":"OTHELLO SCHOOL DISTRICT 147",
      "Location":"OTHELLO, WA",
      "Total Classes":30,
      "Total Teachers":10,
      "Total Students":350,
      "Classes Per Teacher":3.0,
      "Students Per Class":11.67,
      "Algebra Classes":16,
      "Algebra Teachers":16,
      "Algebra Students":315},
    "geometry":{"type":"Point", "coordinates":[-119.1651, 46.8222]},
    "id":96},
   {"type":"Feature",
    "properties":
     {"District":"PASCO SCHOOL DISTRICT 1",
      "Location":"PASCO, WA",
      "Total Classes":1074,
      "Total Teachers":200,
      "Total Students":10502,
      "Classes Per Teacher":5.37,
      "Students Per Class":9.78,
      "Algebra Classes":353,
      "Algebra Teachers":376,
      "Algebra Students":7900},
    "geometry":{"type":"Point", "coordinates":[-119.1303, 46.2506]},
    "id":97},
   {"type":"Feature",
    "properties":
     {"District":"PFLUGERVILLE IND SCH DISTRICT",
      "Location":"PFLUGERVILLE, TX",
      "Total Classes":41,
      "Total Teachers":14,
      "Total Students":989,
      "Classes Per Teacher":2.93,
      "Students Per Class":24.12,
      "Algebra Classes":7,
      "Algebra Teachers":7,
      "Algebra Students":174},
    "geometry":{"type":"Point", "coordinates":[-97.602, 30.4525]},
    "id":98},
   {"type":"Feature",
    "properties":
     {"District":"PHARR-SAN JUAN-ALAMO IND SD",
      "Location":"PHARR, TX",
      "Total Classes":9,
      "Total Teachers":4,
      "Total Students":126,
      "Classes Per Teacher":2.25,
      "Students Per Class":14.0,
      "Algebra Classes":4,
      "Algebra Teachers":4,
      "Algebra Students":80},
    "geometry":{"type":"Point", "coordinates":[-98.1904, 26.1685]},
    "id":99},
   {"type":"Feature",
    "properties":
     {"District":"KIPP PHILADELPHIA",
      "Location":"PHILADELPHIA, PA",
      "Total Classes":19,
      "Total Teachers":8,
      "Total Students":379,
      "Classes Per Teacher":2.38,
      "Students Per Class":19.95,
      "Algebra Classes":15,
      "Algebra Teachers":26,
      "Algebra Students":458},
    "geometry":{"type":"Point", "coordinates":[-75.1339, 40.0077]},
    "id":100},
   {"type":"Feature",
    "properties":
     {"District":"MASTERY CHARTER SCH-GRATZ",
      "Location":"PHILADELPHIA, PA",
      "Total Classes":507,
      "Total Teachers":71,
      "Total Students":4370,
      "Classes Per Teacher":7.14,
      "Students Per Class":8.62,
      "Algebra Classes":265,
      "Algebra Teachers":398,
      "Algebra Students":5659},
    "geometry":{"type":"Point", "coordinates":[-75.1339, 40.0077]},
    "id":101},
   {"type":"Feature",
    "properties":
     {"District":"WEST CATHOLIC PREPARATORY HS",
      "Location":"PHILADELPHIA, PA",
      "Total Classes":55,
      "Total Teachers":7,
      "Total Students":451,
      "Classes Per Teacher":7.86,
      "Students Per Class":8.2,
      "Algebra Classes":30,
      "Algebra Teachers":35,
      "Algebra Students":630},
    "geometry":{"type":"Point", "coordinates":[-75.1339, 40.0077]},
    "id":102},
   {"type":"Feature",
    "properties":
     {"District":"PORTSMOUTH PUBLIC SCHOOLS",
      "Location":"PORTSMOUTH, VA",
      "Total Classes":8,
      "Total Teachers":3,
      "Total Students":74,
      "Classes Per Teacher":2.67,
      "Students Per Class":9.25,
      "Algebra Classes":8,
      "Algebra Teachers":12,
      "Algebra Students":108},
    "geometry":{"type":"Point", "coordinates":[-76.354, 36.8468]},
    "id":103},
   {"type":"Feature",
    "properties":
     {"District":"CROOK CO SCHOOL DISTRICT",
      "Location":"PRINEVILLE, OR",
      "Total Classes":101,
      "Total Teachers":13,
      "Total Students":941,
      "Classes Per Teacher":7.77,
      "Students Per Class":9.32,
      "Algebra Classes":49,
      "Algebra Teachers":63,
      "Algebra Students":1421},
    "geometry":{"type":"Point", "coordinates":[-120.8616, 44.298]},
    "id":104},
   {"type":"Feature",
    "properties":
     {"District":"CALVERT CO PUBLIC SCH DISTRICT",
      "Location":"PRNC FREDERCK, MD",
      "Total Classes":1330,
      "Total Teachers":160,
      "Total Students":9020,
      "Classes Per Teacher":8.31,
      "Students Per Class":6.78,
      "Algebra Classes":330,
      "Algebra Teachers":410,
      "Algebra Students":7737},
    "geometry":{"type":"Point", "coordinates":[-76.5879, 38.544]},
    "id":105},
   {"type":"Feature",
    "properties":
     {"District":"PROSSER SCHOOL DISTRICT 116",
      "Location":"PROSSER, WA",
      "Total Classes":101,
      "Total Teachers":16,
      "Total Students":743,
      "Classes Per Teacher":6.31,
      "Students Per Class":7.36,
      "Algebra Classes":44,
      "Algebra Teachers":61,
      "Algebra Students":1562},
    "geometry":{"type":"Point", "coordinates":[-119.7662, 46.2066]},
    "id":106},
   {"type":"Feature",
    "properties":
     {"District":"RI NURSES INST MID-COLLEGE CS",
      "Location":"PROVIDENCE, RI",
      "Total Classes":37,
      "Total Teachers":9,
      "Total Students":339,
      "Classes Per Teacher":4.11,
      "Students Per Class":9.16,
      "Algebra Classes":11,
      "Algebra Teachers":32,
      "Algebra Students":228},
    "geometry":{"type":"Point", "coordinates":[-71.4187, 41.823]},
    "id":107},
   {"type":"Feature",
    "properties":
     {"District":"TIMES 2 ACADEMY",
      "Location":"PROVIDENCE, RI",
      "Total Classes":41,
      "Total Teachers":7,
      "Total Students":484,
      "Classes Per Teacher":5.86,
      "Students Per Class":11.8,
      "Algebra Classes":7,
      "Algebra Teachers":7,
      "Algebra Students":91},
    "geometry":{"type":"Point", "coordinates":[-71.4187, 41.823]},
    "id":108},
   {"type":"Feature",
    "properties":
     {"District":"RICHLAND PARISH SCHOOL DIST",
      "Location":"RAYVILLE, LA",
      "Total Classes":56,
      "Total Teachers":6,
      "Total Students":581,
      "Classes Per Teacher":9.33,
      "Students Per Class":10.38,
      "Algebra Classes":11,
      "Algebra Teachers":11,
      "Algebra Students":274},
    "geometry":{"type":"Point", "coordinates":[-91.7576, 32.4707]},
    "id":109},
   {"type":"Feature",
    "properties":
     {"District":"REARDAN-EDWALL SCHOOL DIST 9",
      "Location":"REARDAN, WA",
      "Total Classes":14,
      "Total Teachers":4,
      "Total Students":295,
      "Classes Per Teacher":3.5,
      "Students Per Class":21.07,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":88},
    "geometry":{"type":"Point", "coordinates":[-117.8778, 47.6698]},
    "id":110},
   {"type":"Feature",
    "properties":
     {"District":"REVERE PUBLIC SCHOOLS",
      "Location":"REVERE, MA",
      "Total Classes":736,
      "Total Teachers":64,
      "Total Students":4441,
      "Classes Per Teacher":11.5,
      "Students Per Class":6.03,
      "Algebra Classes":156,
      "Algebra Teachers":156,
      "Algebra Students":3310},
    "geometry":{"type":"Point", "coordinates":[-71.0035, 42.4191]},
    "id":111},
   {"type":"Feature",
    "properties":
     {"District":"RICHMOND PUBLIC SCHOOL DISTRICT",
      "Location":"RICHMOND, VA",
      "Total Classes":20,
      "Total Teachers":8,
      "Total Students":382,
      "Classes Per Teacher":2.5,
      "Students Per Class":19.1,
      "Algebra Classes":20,
      "Algebra Teachers":20,
      "Algebra Students":385},
    "geometry":{"type":"Point", "coordinates":[-77.4756, 37.5295]},
    "id":112},
   {"type":"Feature",
    "properties":
     {"District":"GARFIELD SCHOOL DISTRICT RE2",
      "Location":"RIFLE, CO",
      "Total Classes":1,
      "Total Teachers":2,
      "Total Students":25,
      "Classes Per Teacher":0.5,
      "Students Per Class":25.0,
      "Algebra Classes":1,
      "Algebra Teachers":2,
      "Algebra Students":25},
    "geometry":{"type":"Point", "coordinates":[-107.772, 39.5362]},
    "id":113},
   {"type":"Feature",
    "properties":
     {"District":"ACADEMY (AC2E) FOR ACADEMIC ENHANCEMENT MAGNET",
      "Location":"RIO GRANDE CITY, TX",
      "Total Classes":713,
      "Total Teachers":86,
      "Total Students":5169,
      "Classes Per Teacher":8.29,
      "Students Per Class":7.25,
      "Algebra Classes":161,
      "Algebra Teachers":162,
      "Algebra Students":2937},
    "geometry":{"type":"Point", "coordinates":[-98.8216, 26.3808]},
    "id":114},
   {"type":"Feature",
    "properties":
     {"District":"RIO RANCHO PUBLIC SCHOOLS",
      "Location":"RIO RANCHO, NM",
      "Total Classes":20,
      "Total Teachers":17,
      "Total Students":323,
      "Classes Per Teacher":1.18,
      "Students Per Class":16.15,
      "Algebra Classes":8,
      "Algebra Teachers":8,
      "Algebra Students":139},
    "geometry":{"type":"Point", "coordinates":[-106.6981, 35.2872]},
    "id":115},
   {"type":"Feature",
    "properties":
     {"District":"KENT CO PUBLIC SCHOOLS",
      "Location":"ROCK HALL, MD",
      "Total Classes":1,
      "Total Teachers":1,
      "Total Students":17,
      "Classes Per Teacher":1.0,
      "Students Per Class":17.0,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":17},
    "geometry":{"type":"Point", "coordinates":[-76.2427, 39.1393]},
    "id":116},
   {"type":"Feature",
    "properties":
     {"District":"ROGERS PUBLIC SCHOOLS",
      "Location":"ROGERS, AR",
      "Total Classes":481,
      "Total Teachers":44,
      "Total Students":4705,
      "Classes Per Teacher":10.93,
      "Students Per Class":9.78,
      "Algebra Classes":208,
      "Algebra Teachers":208,
      "Algebra Students":5696},
    "geometry":{"type":"Point", "coordinates":[-94.1518, 36.3172]},
    "id":117},
   {"type":"Feature",
    "properties":
     {"District":"RUSSELLVILLE SCHOOL DISTRICT",
      "Location":"RUSSELLVILLE, AR",
      "Total Classes":393,
      "Total Teachers":31,
      "Total Students":3252,
      "Classes Per Teacher":12.68,
      "Students Per Class":8.27,
      "Algebra Classes":116,
      "Algebra Teachers":116,
      "Algebra Students":2031},
    "geometry":{"type":"Point", "coordinates":[-93.1383, 35.2763]},
    "id":118},
   {"type":"Feature",
    "properties":
     {"District":"LINCOLN PARISH SCHOOL DISTRICT",
      "Location":"RUSTON, LA",
      "Total Classes":128,
      "Total Teachers":20,
      "Total Students":1564,
      "Classes Per Teacher":6.4,
      "Students Per Class":12.22,
      "Algebra Classes":66,
      "Algebra Teachers":79,
      "Algebra Students":1351},
    "geometry":{"type":"Point", "coordinates":[-92.6361, 32.5329]},
    "id":119},
   {"type":"Feature",
    "properties":
     {"District":"ST JOHN SCHOOL DISTRICT 322",
      "Location":"SAINT JOHN, WA",
      "Total Classes":14,
      "Total Teachers":2,
      "Total Students":103,
      "Classes Per Teacher":7.0,
      "Students Per Class":7.36,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":7},
    "geometry":{"type":"Point", "coordinates":[-117.5887, 47.0915]},
    "id":120},
   {"type":"Feature",
    "properties":
     {"District":"TENSAS PARISH SCHOOL DISTRICT",
      "Location":"SAINT JOSEPH, LA",
      "Total Classes":32,
      "Total Teachers":4,
      "Total Students":243,
      "Classes Per Teacher":8.0,
      "Students Per Class":7.59,
      "Algebra Classes":8,
      "Algebra Teachers":8,
      "Algebra Students":172},
    "geometry":{"type":"Point", "coordinates":[-91.2401, 31.9202]},
    "id":121},
   {"type":"Feature",
    "properties":
     {"District":"SEATTLE PUBLIC SCHOOLS",
      "Location":"SEATTLE, WA",
      "Total Classes":2,
      "Total Teachers":1,
      "Total Students":35,
      "Classes Per Teacher":2.0,
      "Students Per Class":17.5,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":35},
    "geometry":{"type":"Point", "coordinates":[-122.3244, 47.6211]},
    "id":122},
   {"type":"Feature",
    "properties":
     {"District":"SEQUIM SCHOOL DISTRICT 323",
      "Location":"SEQUIM, WA",
      "Total Classes":27,
      "Total Teachers":3,
      "Total Students":315,
      "Classes Per Teacher":9.0,
      "Students Per Class":11.67,
      "Algebra Classes":11,
      "Algebra Teachers":11,
      "Algebra Students":293},
    "geometry":{"type":"Point", "coordinates":[-123.0944, 48.0747]},
    "id":123},
   {"type":"Feature",
    "properties":
     {"District":"SIMMS IND SCHOOL DISTRICT",
      "Location":"SIMMS, TX",
      "Total Classes":2,
      "Total Teachers":1,
      "Total Students":23,
      "Classes Per Teacher":2.0,
      "Students Per Class":11.5,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":23},
    "geometry":{"type":"Point", "coordinates":[-94.5074, 33.3504]},
    "id":124},
   {"type":"Feature",
    "properties":
     {"District":"SNYDER IND SCHOOL DISTRICT",
      "Location":"SNYDER, TX",
      "Total Classes":5,
      "Total Teachers":3,
      "Total Students":77,
      "Classes Per Teacher":1.67,
      "Students Per Class":15.4,
      "Algebra Classes":5,
      "Algebra Teachers":8,
      "Algebra Students":104},
    "geometry":{"type":"Point", "coordinates":[-100.9113, 32.7133]},
    "id":125},
   {"type":"Feature",
    "properties":
     {"District":"BETHEL SCHOOL DISTRICT 403",
      "Location":"SPANAWAY, WA",
      "Total Classes":33,
      "Total Teachers":11,
      "Total Students":589,
      "Classes Per Teacher":3.0,
      "Students Per Class":17.85,
      "Algebra Classes":33,
      "Algebra Teachers":40,
      "Algebra Students":873},
    "geometry":{"type":"Point", "coordinates":[-122.4233, 47.0979]},
    "id":126},
   {"type":"Feature",
    "properties":
     {"District":"MAPLE RUN UNIFIED SCHOOL DISTRICT",
      "Location":"ST. ALBANS, VT",
      "Total Classes":3,
      "Total Teachers":3,
      "Total Students":55,
      "Classes Per Teacher":1.0,
      "Students Per Class":18.33,
      "Algebra Classes":3,
      "Algebra Teachers":6,
      "Algebra Students":55},
    "geometry":{"type":"Point", "coordinates":[-73.0846, 44.8118]},
    "id":127},
   {"type":"Feature",
    "properties":
     {"District":"STANWOOD-CAMANO SCH DIST 401",
      "Location":"STANWOOD, WA",
      "Total Classes":8,
      "Total Teachers":2,
      "Total Students":167,
      "Classes Per Teacher":4.0,
      "Students Per Class":20.88,
      "Algebra Classes":8,
      "Algebra Teachers":8,
      "Algebra Students":175},
    "geometry":{"type":"Point", "coordinates":[-122.3426, 48.2451]},
    "id":128},
   {"type":"Feature",
    "properties":
     {"District":"MARTIN CO SCHOOL DISTRICT",
      "Location":"STUART, FL",
      "Total Classes":7,
      "Total Teachers":3,
      "Total Students":109,
      "Classes Per Teacher":2.33,
      "Students Per Class":15.57,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":24},
    "geometry":{"type":"Point", "coordinates":[-80.2438, 27.1958]},
    "id":129},
   {"type":"Feature",
    "properties":
     {"District":"SUMNER SCHOOL DISTRICT 404",
      "Location":"SUMNER, WA",
      "Total Classes":13,
      "Total Teachers":6,
      "Total Students":229,
      "Classes Per Teacher":2.17,
      "Students Per Class":17.62,
      "Algebra Classes":12,
      "Algebra Teachers":13,
      "Algebra Students":314},
    "geometry":{"type":"Point", "coordinates":[-122.2338, 47.219]},
    "id":130},
   {"type":"Feature",
    "properties":
     {"District":"SYRACUSE CITY SCHOOL DISTRICT",
      "Location":"SYRACUSE, NY",
      "Total Classes":8,
      "Total Teachers":4,
      "Total Students":84,
      "Classes Per Teacher":2.0,
      "Students Per Class":10.5,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":35},
    "geometry":{"type":"Point", "coordinates":[-76.1438, 43.0409]},
    "id":131},
   {"type":"Feature",
    "properties":
     {"District":"PEPIN ACADEMIES-TAMPA",
      "Location":"TAMPA, FL",
      "Total Classes":6,
      "Total Teachers":2,
      "Total Students":81,
      "Classes Per Teacher":3.0,
      "Students Per Class":13.5,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":85},
    "geometry":{"type":"Point", "coordinates":[-82.4451, 27.9942]},
    "id":132},
   {"type":"Feature",
    "properties":
     {"District":"LIBERTY-EYLAU IND SCH DISTRICT",
      "Location":"TEXARKANA, TX",
      "Total Classes":1,
      "Total Teachers":1,
      "Total Students":18,
      "Classes Per Teacher":1.0,
      "Students Per Class":18.0,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":18},
    "geometry":{"type":"Point", "coordinates":[-94.0815, 33.4487]},
    "id":133},
   {"type":"Feature",
    "properties":
     {"District":"TULSA PUBLIC SCHOOLS",
      "Location":"TULSA, OK",
      "Total Classes":51,
      "Total Teachers":13,
      "Total Students":1282,
      "Classes Per Teacher":3.92,
      "Students Per Class":25.14,
      "Algebra Classes":17,
      "Algebra Teachers":17,
      "Algebra Students":459},
    "geometry":{"type":"Point", "coordinates":[-95.9043, 36.1284]},
    "id":134},
   {"type":"Feature",
    "properties":
     {"District":"TOWNSHIP OF UNION PUBLIC SCHOOLS",
      "Location":"UNION, NJ",
      "Total Classes":187,
      "Total Teachers":21,
      "Total Students":1997,
      "Classes Per Teacher":8.9,
      "Students Per Class":10.68,
      "Algebra Classes":75,
      "Algebra Teachers":76,
      "Algebra Students":1042},
    "geometry":{"type":"Point", "coordinates":[-74.2632, 40.6976]},
    "id":135},
   {"type":"Feature",
    "properties":
     {"District":"VALLEY CENTER-PAUMA UNIFIED SD",
      "Location":"VALLEY CENTER, CA",
      "Total Classes":5,
      "Total Teachers":3,
      "Total Students":100,
      "Classes Per Teacher":1.67,
      "Students Per Class":20.0,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":106},
    "geometry":{"type":"Point", "coordinates":[-117.0158, 33.2331]},
    "id":136},
   {"type":"Feature",
    "properties":
     {"District":"CULBERSON CO ALLAMOORE IND SD",
      "Location":"VAN HORN, TX",
      "Total Classes":36,
      "Total Teachers":6,
      "Total Students":228,
      "Classes Per Teacher":6.0,
      "Students Per Class":6.33,
      "Algebra Classes":13,
      "Algebra Teachers":16,
      "Algebra Students":215},
    "geometry":{"type":"Point", "coordinates":[-104.834, 31.0407]},
    "id":137},
   {"type":"Feature",
    "properties":
     {"District":"VANCOUVER SCHOOL DISTRICT 37",
      "Location":"VANCOUVER, WA",
      "Total Classes":582,
      "Total Teachers":109,
      "Total Students":6023,
      "Classes Per Teacher":5.34,
      "Students Per Class":10.35,
      "Algebra Classes":283,
      "Algebra Teachers":309,
      "Algebra Students":7744},
    "geometry":{"type":"Point", "coordinates":[-122.597, 45.6367]},
    "id":138},
   {"type":"Feature",
    "properties":
     {"District":"VICKSBURG CMTY SCHOOL DISTRICT",
      "Location":"VICKSBURG, MI",
      "Total Classes":62,
      "Total Teachers":15,
      "Total Students":1092,
      "Classes Per Teacher":4.13,
      "Students Per Class":17.61,
      "Algebra Classes":12,
      "Algebra Teachers":16,
      "Algebra Students":322},
    "geometry":{"type":"Point", "coordinates":[-85.5412, 42.1186]},
    "id":139},
   {"type":"Feature",
    "properties":
     {"District":"CONCORDIA PARISH SCHOOL DIST",
      "Location":"VIDALIA, LA",
      "Total Classes":324,
      "Total Teachers":38,
      "Total Students":1986,
      "Classes Per Teacher":8.53,
      "Students Per Class":6.13,
      "Algebra Classes":94,
      "Algebra Teachers":96,
      "Algebra Students":1675},
    "geometry":{"type":"Point", "coordinates":[-91.4405, 31.5668]},
    "id":140},
   {"type":"Feature",
    "properties":
     {"District":"WAPATO SCHOOL DISTRICT 207",
      "Location":"WAPATO, WA",
      "Total Classes":190,
      "Total Teachers":17,
      "Total Students":1835,
      "Classes Per Teacher":11.18,
      "Students Per Class":9.66,
      "Algebra Classes":42,
      "Algebra Teachers":46,
      "Algebra Students":1117},
    "geometry":{"type":"Point", "coordinates":[-120.4215, 46.4434]},
    "id":141},
   {"type":"Feature",
    "properties":
     {"District":"WARWICK PUBLIC SCHOOLS",
      "Location":"WARWICK, RI",
      "Total Classes":209,
      "Total Teachers":54,
      "Total Students":2408,
      "Classes Per Teacher":3.87,
      "Students Per Class":11.52,
      "Algebra Classes":108,
      "Algebra Teachers":139,
      "Algebra Students":2241},
    "geometry":{"type":"Point", "coordinates":[-71.4334, 41.7062]},
    "id":142},
   {"type":"Feature",
    "properties":
     {"District":"CESAR CHAVEZ PUBLIC POLICY CHARTER",
      "Location":"WASHINGTON, DC",
      "Total Classes":54,
      "Total Teachers":12,
      "Total Students":468,
      "Classes Per Teacher":4.5,
      "Students Per Class":8.67,
      "Algebra Classes":18,
      "Algebra Teachers":18,
      "Algebra Students":398},
    "geometry":{"type":"Point", "coordinates":[-77.0163, 38.9047]},
    "id":143},
   {"type":"Feature",
    "properties":
     {"District":"DC PREPARATORY ACADEMY MID SCH",
      "Location":"WASHINGTON, DC",
      "Total Classes":22,
      "Total Teachers":5,
      "Total Students":133,
      "Classes Per Teacher":4.4,
      "Students Per Class":6.05,
      "Algebra Classes":12,
      "Algebra Teachers":15,
      "Algebra Students":133},
    "geometry":{"type":"Point", "coordinates":[-77.0163, 38.9047]},
    "id":144},
   {"type":"Feature",
    "properties":
     {"District":"WAUKESHA SCHOOL DISTRICT",
      "Location":"WAUKESHA, WI",
      "Total Classes":826,
      "Total Teachers":57,
      "Total Students":4239,
      "Classes Per Teacher":14.49,
      "Students Per Class":5.13,
      "Algebra Classes":263,
      "Algebra Teachers":265,
      "Algebra Students":5414},
    "geometry":{"type":"Point", "coordinates":[-88.2464, 43.0087]},
    "id":145},
   {"type":"Feature",
    "properties":
     {"District":"WESTERLY PUBLIC SCH DISTRICT",
      "Location":"WESTERLY, RI",
      "Total Classes":96,
      "Total Teachers":16,
      "Total Students":862,
      "Classes Per Teacher":6.0,
      "Students Per Class":8.98,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":141},
    "geometry":{"type":"Point", "coordinates":[-71.8273, 41.3776]},
    "id":146},
   {"type":"Feature",
    "properties":
     {"District":"MT ADAMS SCHOOL DISTRICT 209",
      "Location":"WHITE SWAN, WA",
      "Total Classes":38,
      "Total Teachers":6,
      "Total Students":316,
      "Classes Per Teacher":6.33,
      "Students Per Class":8.32,
      "Algebra Classes":10,
      "Algebra Teachers":10,
      "Algebra Students":189},
    "geometry":{"type":"Point", "coordinates":[-120.7382, 46.3769]},
    "id":147},
   {"type":"Feature",
    "properties":
     {"District":"WOODLAND SCHOOL DISTRICT 404",
      "Location":"WOODLAND, WA",
      "Total Classes":14,
      "Total Teachers":3,
      "Total Students":155,
      "Classes Per Teacher":4.67,
      "Students Per Class":11.07,
      "Algebra Classes":6,
      "Algebra Teachers":7,
      "Algebra Students":146},
    "geometry":{"type":"Point", "coordinates":[-122.7503, 45.9149]},
    "id":148},
   {"type":"Feature",
    "properties":
     {"District":"WOODSTOCK CMTY UNIT SD 200",
      "Location":"WOODSTOCK, IL",
      "Total Classes":9,
      "Total Teachers":6,
      "Total Students":201,
      "Classes Per Teacher":1.5,
      "Students Per Class":22.33,
      "Algebra Classes":9,
      "Algebra Teachers":9,
      "Algebra Students":231},
    "geometry":{"type":"Point", "coordinates":[-88.4357, 42.3103]},
    "id":149},
   {"type":"Feature",
    "properties":
     {"District":"YAKIMA SCHOOL DISTRICT 7",
      "Location":"YAKIMA, WA",
      "Total Classes":122,
      "Total Teachers":17,
      "Total Students":1579,
      "Classes Per Teacher":7.18,
      "Students Per Class":12.94,
      "Algebra Classes":21,
      "Algebra Teachers":21,
      "Algebra Students":561},
    "geometry":{"type":"Point", "coordinates":[-120.5496, 46.5923]},
    "id":150},
   {"type":"Feature",
    "properties":
     {"District":"WEST YORK AREA SCHOOL DISTRICT",
      "Location":"YORK, PA",
      "Total Classes":1,
      "Total Teachers":1,
      "Total Students":14,
      "Classes Per Teacher":1.0,
      "Students Per Class":14.0,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":14},
    "geometry":{"type":"Point", "coordinates":[-76.7315, 39.9651]},
    "id":151},
   {"type":"Feature",
    "properties":
     {"District":"YORK CITY SCHOOL DISTRICT",
      "Location":"YORK, PA",
      "Total Classes":8,
      "Total Teachers":3,
      "Total Students":154,
      "Classes Per Teacher":2.67,
      "Students Per Class":19.25,
      "Algebra Classes":8,
      "Algebra Teachers":10,
      "Algebra Students":158},
    "geometry":{"type":"Point", "coordinates":[-76.7315, 39.9651]},
    "id":152},
   {"type":"Feature",
    "properties":
     {"District":"YORK CO SCHOOL OF TECHNOLOGY",
      "Location":"YORK, PA",
      "Total Classes":34,
      "Total Teachers":7,
      "Total Students":497,
      "Classes Per Teacher":4.86,
      "Students Per Class":14.62,
      "Algebra Classes":34,
      "Algebra Teachers":41,
      "Algebra Students":565},
    "geometry":{"type":"Point", "coordinates":[-76.7315, 39.9651]},
    "id":153},
   {"type":"Feature",
    "properties":
     {"District":"VALLEY CHRISTIAN SCHOOLS MAIN CAMPUS",
      "Location":"YOUNGSTOWN, OH",
      "Total Classes":43,
      "Total Teachers":6,
      "Total Students":203,
      "Classes Per Teacher":7.17,
      "Students Per Class":4.72,
      "Algebra Classes":15,
      "Algebra Teachers":25,
      "Algebra Students":180},
    "geometry":{"type":"Point", "coordinates":[-80.6463, 41.0993]},
    "id":154},
   {"type":"Feature",
    "properties":
     {"District":"ZACHARY COMMUNITY SCHOOL DIST",
      "Location":"ZACHARY, LA",
      "Total Classes":154,
      "Total Teachers":24,
      "Total Students":1588,
      "Classes Per Teacher":6.42,
      "Students Per Class":10.31,
      "Algebra Classes":64,
      "Algebra Teachers":68,
      "Algebra Students":1785},
    "geometry":{"type":"Point", "coordinates":[-91.1634, 30.6642]},
    "id":155},
   {"type":"Feature",
    "properties":
     {"District":"ZEIGLER ROYALTON CUSD 188",
      "Location":"ZEIGLER, IL",
      "Total Classes":36,
      "Total Teachers":6,
      "Total Students":222,
      "Classes Per Teacher":6.0,
      "Students Per Class":6.17,
      "Algebra Classes":12,
      "Algebra Teachers":20,
      "Algebra Students":135},
    "geometry":{"type":"Point", "coordinates":[-89.0521, 37.9067]},
    "id":156},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":36,
      "Total Teachers":6,
      "Total Students":333,
      "Classes Per Teacher":6.0,
      "Students Per Class":9.25,
      "Algebra Classes":11,
      "Algebra Teachers":11,
      "Algebra Students":167},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":157},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":6,
      "Total Teachers":2,
      "Total Students":157,
      "Classes Per Teacher":3.0,
      "Students Per Class":26.17,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":262},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":158},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":53,
      "Total Teachers":8,
      "Total Students":490,
      "Classes Per Teacher":6.63,
      "Students Per Class":9.25,
      "Algebra Classes":19,
      "Algebra Teachers":26,
      "Algebra Students":379},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":159},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":24,
      "Total Teachers":7,
      "Total Students":214,
      "Classes Per Teacher":3.43,
      "Students Per Class":8.92,
      "Algebra Classes":12,
      "Algebra Teachers":20,
      "Algebra Students":219},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":160},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":7,
      "Total Teachers":4,
      "Total Students":115,
      "Classes Per Teacher":1.75,
      "Students Per Class":16.43,
      "Algebra Classes":7,
      "Algebra Teachers":7,
      "Algebra Students":115},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":161},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":86,
      "Total Teachers":16,
      "Total Students":982,
      "Classes Per Teacher":5.38,
      "Students Per Class":11.42,
      "Algebra Classes":58,
      "Algebra Teachers":58,
      "Algebra Students":1049},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":162},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":14,
      "Total Teachers":6,
      "Total Students":603,
      "Classes Per Teacher":2.33,
      "Students Per Class":43.07,
      "Algebra Classes":3,
      "Algebra Teachers":6,
      "Algebra Students":604},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":163},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":33,
      "Total Teachers":10,
      "Total Students":613,
      "Classes Per Teacher":3.3,
      "Students Per Class":18.58,
      "Algebra Classes":15,
      "Algebra Teachers":55,
      "Algebra Students":466},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":164},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":63,
      "Total Teachers":9,
      "Total Students":562,
      "Classes Per Teacher":7.0,
      "Students Per Class":8.92,
      "Algebra Classes":32,
      "Algebra Teachers":40,
      "Algebra Students":715},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":165},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":6,
      "Total Teachers":1,
      "Total Students":71,
      "Classes Per Teacher":6.0,
      "Students Per Class":11.83,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":72},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":166},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":25,
      "Total Teachers":18,
      "Total Students":446,
      "Classes Per Teacher":1.39,
      "Students Per Class":17.84,
      "Algebra Classes":25,
      "Algebra Teachers":41,
      "Algebra Students":596},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":167},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":7,
      "Total Teachers":3,
      "Total Students":158,
      "Classes Per Teacher":2.33,
      "Students Per Class":22.57,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":61},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":168},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":2,
      "Total Teachers":1,
      "Total Students":41,
      "Classes Per Teacher":2.0,
      "Students Per Class":20.5,
      "Algebra Classes":2,
      "Algebra Teachers":2,
      "Algebra Students":42},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":169},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":13,
      "Total Teachers":2,
      "Total Students":148,
      "Classes Per Teacher":6.5,
      "Students Per Class":11.38,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":125},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":170},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":14,
      "Total Teachers":6,
      "Total Students":144,
      "Classes Per Teacher":2.33,
      "Students Per Class":10.29,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":64},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":171},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":10,
      "Total Teachers":3,
      "Total Students":94,
      "Classes Per Teacher":3.33,
      "Students Per Class":9.4,
      "Algebra Classes":5,
      "Algebra Teachers":5,
      "Algebra Students":94},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":172},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":1,
      "Total Teachers":2,
      "Total Students":16,
      "Classes Per Teacher":0.5,
      "Students Per Class":16.0,
      "Algebra Classes":1,
      "Algebra Teachers":2,
      "Algebra Students":16},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":173},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":12,
      "Total Teachers":1,
      "Total Students":72,
      "Classes Per Teacher":12.0,
      "Students Per Class":6.0,
      "Algebra Classes":6,
      "Algebra Teachers":6,
      "Algebra Students":78},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":174},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":26,
      "Total Teachers":4,
      "Total Students":202,
      "Classes Per Teacher":6.5,
      "Students Per Class":7.77,
      "Algebra Classes":13,
      "Algebra Teachers":13,
      "Algebra Students":384},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":175},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":7,
      "Total Teachers":1,
      "Total Students":72,
      "Classes Per Teacher":7.0,
      "Students Per Class":10.29,
      "Algebra Classes":3,
      "Algebra Teachers":3,
      "Algebra Students":54},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":176},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":162,
      "Total Teachers":34,
      "Total Students":1144,
      "Classes Per Teacher":4.76,
      "Students Per Class":7.06,
      "Algebra Classes":63,
      "Algebra Teachers":139,
      "Algebra Students":1236},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":177},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":5,
      "Total Teachers":2,
      "Total Students":43,
      "Classes Per Teacher":2.5,
      "Students Per Class":8.6,
      "Algebra Classes":1,
      "Algebra Teachers":1,
      "Algebra Students":5},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":178},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":1,
      "Total Teachers":2,
      "Total Students":23,
      "Classes Per Teacher":0.5,
      "Students Per Class":23.0,
      "Algebra Classes":1,
      "Algebra Teachers":2,
      "Algebra Students":23},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":179},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":43,
      "Total Teachers":14,
      "Total Students":353,
      "Classes Per Teacher":3.07,
      "Students Per Class":8.21,
      "Algebra Classes":1,
      "Algebra Teachers":2,
      "Algebra Students":25},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":180},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":4,
      "Total Teachers":4,
      "Total Students":250,
      "Classes Per Teacher":1.0,
      "Students Per Class":62.5,
      "Algebra Classes":2,
      "Algebra Teachers":4,
      "Algebra Students":250},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":181},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":20,
      "Total Teachers":5,
      "Total Students":95,
      "Classes Per Teacher":4.0,
      "Students Per Class":4.75,
      "Algebra Classes":4,
      "Algebra Teachers":6,
      "Algebra Students":102},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":182},
   {"type":"Feature",
    "properties":
     {"District":"City Unknown",
      "Location":"FAIRBANKS, AK",
      "Total Classes":55,
      "Total Teachers":9,
      "Total Students":631,
      "Classes Per Teacher":6.11,
      "Students Per Class":11.47,
      "Algebra Classes":25,
      "Algebra Teachers":34,
      "Algebra Students":598},
    "geometry":{"type":"Point", "coordinates":[-147.6534, 64.8353]},
    "id":183}]}`)
    );
}

// Defines the callback function referenced in the jsonp file.
function eqfeed_callback(data) {
    map.data.addGeoJson(data);

    map.data.addListener('mouseover', (event) => {
        if (infoSticky)
            return;

        const myHTML = "District: " + event.feature.getProperty("District") + "<br/>Algebra Classes: " + event.feature.getProperty("Algebra Classes");
        infoWindow.setContent("<div style='width:150px;'>"+myHTML+"</div>");
        // position the infoWindow on the marker
        infoWindow.setPosition(event.feature.getGeometry().get());
        // anchor the infoWindow on the marker
        infoWindow.setOptions({pixelOffset: new google.maps.Size(0,-30)});
        infoWindow.open(map);
    });
    map.data.addListener('mouseout', () => {
        if (infoSticky)
            return;
        infoWindow.close();
    });

    map.data.addListener('click', (event) => {
        let myHTML = "";
        event.feature.forEachProperty((v, k) => {
            if (myHTML !== "") {
                myHTML = myHTML + "<br />";
            }
            myHTML = myHTML + k + ": " + v;
        });
        infoWindow.setContent("<div style='width:150px;'>"+myHTML+"</div>");
        changeSticky(true);
    });
    infoWindow.addListener('closeclick', () => changeSticky(false));
}

function changeSticky(sticky) {
    const closeControl = document.querySelector('#map .gm-ui-hover-effect');
    if (sticky) {
        closeControl.classList.add('show');
    } else {
        closeControl.classList.remove('show');
    }
    infoSticky = sticky;
}

function styleFeature(feature) {
    const low = [151, 83, 34]; // color of mag 1.0
    const high = [5, 69, 54]; // color of mag 6.0 and above
    const minMag = 1.0;
    const maxMag = 960.0;
    const mag = feature.getProperty("Algebra Classes");
    // fraction represents where the value sits between the min and max
    const fraction =
        (Math.min(mag, maxMag) - minMag) / (maxMag - minMag);
    const color = interpolateHsl(low, high, fraction);
    const style = {
        icon: {
            path: google.maps.SymbolPath.CIRCLE,
            strokeWeight: 0.5,
            strokeColor: "#fff",
            fillColor: color,
            fillOpacity: 2 / mag,
            scale: 3 + Math.max(1, fraction * 20),
        },
        name: feature.getProperty("Location"),
        zIndex: Math.floor(mag),
    };
    console.log(feature);
    return style;
}

function interpolateHsl(lowHsl, highHsl, fraction) {
    const color = [];

    for (let i = 0; i < 3; i++) {
        // Calculate color based on the fraction.
        color.push((highHsl[i] - lowHsl[i]) * fraction + lowHsl[i]);
    }
    return "hsl(" + color[0] + "," + color[1] + "%," + color[2] + "%)";
}

const mapStyle = [
    {
        "featureType": "administrative.country",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.land_parcel",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "administrative.neighborhood",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.school",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    }
];


async function loadData(url) {
    try {
        const response = await fetch(url, {
            mode: 'no-cors'
        });
        const data = await response.text();
        console.log(data);
    } catch (err) {
        console.error(err);
    }
}
